version: "3.3"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  # mysql:
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_DATABASE=my_store
  #     - MYSQL_USER=ivan
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - MYSQL_ROOT_HOST=3306
  #   ports:
  #     - "2007:2006"
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - PMA_HOST=mysql
  #   ports:
  #     - 8080:80